name: Feature request
description: Suggest an idea for this project
labels: [feature request, needs triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to make this fork of `NewPipe` better by suggesting a feature. :hugs:

        Your ideas are highly welcome! The app is made for you, the users, after all.
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are *no feature requests* - [open](https://github.com/NewPipeX/NewPipeX/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22) or [closed](https://github.com/NewPipeX/NewPipeX/issues?q=is%3Aissue+is%3Aclosed+label%3A%22feature+request%22) - that already cover my request."
          required: true
        - label: "My feature request has a well-defined scope and is described in sufficient detail."
          required: true
        - label: "I understand and accept that my feature request may not be considered unless it can attract significant community support."
          required: true
        - label: "I have read and understood the [contribution guidelines](https://github.com/NewPipeX/NewPipeX/blob/sponsorblock/.github/CONTRIBUTING.md)."
          required: true
        - label: "I am positive that my feature request meets *one* of the following criteria, and I have checked the *one* box that applies to my feature request below:"
          required: true
        - label: "My feature request relates to fork-specific functionality that does not exist upstream (e.g., `SponsorBlock`, `Return YouTube Dislike`)."
          required: false
        - label: "My feature request has already been opened upstream, _and_ it has been declined."
          required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Explain how you want the app's look or behavior to change.
    validations:
      required: true

  - type: textarea
    id: why-is-the-feature-requested
    attributes:
      label: Why do you want this feature?
      description: |
        Describe any problem or limitation you come across while using the app which would be solved by this feature.
    validations:
      required: true

  - type: textarea
    id: why-relevant-to-fork
    attributes:
      label: Why is this feature relevant to this fork?
      description: |
        Describe why this feature is relevant to this fork's specific functionality that does not exist upstream OR demonstrate that this feature has already been requested [upstream](https://github.com/TeamNewPipe/NewPipe/issues), and it was *explicitly* declined.

        (This is not the place for stale upstream feature requests!)
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include, for instance sketches, mockups, pictures of cats, etc.
